# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: a87dcae6b0c9a0e42092e21baeb6f3983281543f18c400f3a8082cee2d87b972c5c965893bdda67023ff5aa7c1f44fea677d9eecfabd50edc0c949294f1d9b4f

test:
  secret_key_base: 5ca2a04280cd00f311bd1342cf243443de72550b586dd8f6c11056ccdc3874579a7089c43d460c46ac1fe8061ea19cf23ad20e2d8cb4f6d012c3bf0961b1a89d

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
